services:
  motis-web-deploy:
    image: ghcr.io/motis-project/motis-web-deploy:master
    environment:
      - ORIGIN=https://run.motis-project.de
    volumes:
      - ./instances:/instances
      - ./motis:/motis
    ports:
      - "3000:3000"
    restart: unless-stopped