services:
  motis-web-deploy:
    image: ghcr.io/motis-project/motis-web-deploy:master
    environment:
      - ORIGIN=https://run.motis-project.de
      - BODY_SIZE_LIMIT=Infinity
      - MOTIS_FOLDER=/motis
      - INSTANCE_FOLDER=/instances
    volumes:
      - ./instances:/instances
      - ./motis:/motis
    ports:
      - "3000:3000"
    restart: unless-stopped